development:
  secret_key_base: 21d8c371b86b29c18b38a19a53b1b649e712065956640979cf6bfd3a395eb9be6ae11a1161274f89bd8b9d55b443b70612ee661384e75a165a034c2f091489b9

test:
  secret_key_base: 8072fb73f2788dc82cd1cf6893386c4e960829f5225d43742355a501eb4fdb05f0dbbb438a41c4dc2f9c443ac29843117980e8f5e34710616c820265c448c765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8072fb73f2788dc82cd1cf6893386c4e960829f5225d43742355a501eb4fdb05f0dbbb438a41c4dc2f9c443ac29843117980e8f5e34710616c820265c448c765
  secret_token: 8072fb73f2788dc82cd1cf6893386c4e960829f5225d43742355a501eb4fdb05f0dbbb438a41c4dc2f9c443ac29843117980e8f5e34710616c820265c448c765

staging:
  secret_key_base: a84d33caa59f83b84cc614ab89c7944f576514a5ccf712dd84c65d1338cb806ab2f9c1ce9b3c177e75d27df801832b477cb267aac5cf9f586f4edc54f9dbc385
  secret_token: a84d33caa59f83b84cc614ab89c7944f576514a5ccf712dd84c65d1338cb806ab2f9c1ce9b3c177e75d27df801832b477cb267aac5cf9f586f4edc54f9dbc385
